name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        composer: [highest, lowest]
        php-versions: ['8.4']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - uses: "ramsey/composer-install@v3"
      with:
          dependency-versions: ${{ matrix.composer }}

    - name: Run Pest
      run: ./vendor/bin/pest

  pint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - run: composer install

    - name: Run Pint
      run: ./vendor/bin/pint --test
